apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: open-eureka-server
  namespace: dop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: open-eureka-server
    spec:
      containers:
      - name: open-eureka-server
        image: docker.io/clsaa/open-eureka-server
        ports:
          containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: open-eureka-server
  namespace: dop
  labels:
    app: open-eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: open-eureka-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: open-eureka-server
  namespace: dop
spec:
  rules:
  - host: eureka.dop.k8s.clsaa.com
    http:
      paths:
      - backend:
          serviceName: open-eureka-server
          servicePort: 8761