spring:
  application:
    name: open-eureka-server  #服务名
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: localhost  # 指定该Eureka实例的主机名
    appname: ${spring.application.name}  #服务名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/